name: kelishamiz
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^14.2.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  dio: ^5.6.0
  hive: ^2.2.3
  shared_preferences: ^2.3.2
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/nav_icons/
    - assets/icons/transport_icons/
    - assets/icons/real_estate_icons/
    - assets/icons/service_icons/
    - assets/icons/electronics_icons/
    - assets/icons/construction_icons/
    - assets/icons/garden_icons/
    - assets/icons/personal_icons/
    - assets/icons/production_icons/
    - assets/icons/other_icons/
    - assets/icons/profile_icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  
